apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: rr0ro57gk-dotnet-basic
  janus-idp.io/tekton: rr0ro57gk-dotnet-basic
  backstage.io/kubernetes-id: rr0ro57gk-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rr0ro57gk-dotnet-basic
resources:
- deployment.yaml
- route.yaml
- service.yaml
